import 'package:get/get.dart';
import 'package:request_hr/app/alert/alert-details/controllers/alert_details_controller.dart';
import 'package:request_hr/app/alert/main/controllers/alert_controller.dart';
import 'package:request_hr/app/bonus/bonus-details/controllers/bonus_details_controller.dart';
import 'package:request_hr/app/bonus/main/controllers/bonus_controller.dart';
import 'package:request_hr/app/complaint/complaint-details/controllers/complaint_details_controller.dart';
import 'package:request_hr/app/complaint/main/controllers/complaint_controller.dart';
import 'package:request_hr/app/custody/custody-details/controllers/custody_details_controller.dart';
import 'package:request_hr/app/custody/main/controllers/custody_controller.dart';
import 'package:request_hr/app/dashboard/main/controller/dashboard-controller.dart';
import 'package:request_hr/app/dashboard/tabs/decisions/decision-details/controllers/decisions_details_controller.dart';
import 'package:request_hr/app/dashboard/tabs/decisions/main/controllers/decisions_controller.dart';
import 'package:request_hr/app/dashboard/tabs/home/controllers/home_controller.dart';
import 'package:request_hr/app/dashboard/tabs/meetings/main/controllers/meetings_controller.dart';
import 'package:request_hr/app/dashboard/tabs/meetings/meetings-details/controllers/meetings_details_controller.dart';
import 'package:request_hr/app/dashboard/tabs/vacations/main/controllers/vacations_controller.dart';
import 'package:request_hr/app/dashboard/tabs/vacations/success-vacation/controllers/success_vacation_controller.dart';
import 'package:request_hr/app/dashboard/tabs/vacations/vacation-form/controllers/vacations_form_controller.dart';
import 'package:request_hr/app/dashboard/tabs/vacations/vacation-steps/main/controllers/vacations_steps_controller.dart';
import 'package:request_hr/app/delete/controllers/delete_controller.dart';
import 'package:request_hr/app/evaluations/evaluations-steps/main/controllers/evaluations_steps_controller.dart';
import 'package:request_hr/app/evaluations/main/controllers/evaluations_controller.dart';
import 'package:request_hr/app/loan/loan-details/controllers/loan_details_controller.dart';
import 'package:request_hr/app/loan/main/controllers/loan_controller.dart';
import 'package:request_hr/app/mail/create-mail/controllers/create_mail_controller.dart';
import 'package:request_hr/app/mail/mail-details/controllers/mail_details_controller.dart';
import 'package:request_hr/app/mail/main/controllers/mail_controller.dart';
import 'package:request_hr/app/notification/controllers/notifications_controller.dart';
import 'package:request_hr/app/punishments/main/controllers/punishments_controller.dart';
import 'package:request_hr/app/punishments/punishments-details/controllers/punishments_details_controller.dart';
import 'package:request_hr/app/purchase/main/controllers/purchase_controller.dart';
import 'package:request_hr/app/settings/controllers/settings_controller.dart';
import 'package:request_hr/app/sign-in-out/main/controllers/sign_in_out_controller.dart';
import 'package:request_hr/app/sign-in-out/sign-in-out-details/controllers/sign_in_out_details_controller.dart';
import 'package:request_hr/app/ticket/main/controllers/ticket_controller.dart';
import 'package:request_hr/app/ticket/ticket-details/controllers/ticket_details_controller.dart';

import '../../app/auth/login/controllers/login_controller.dart';

class Binding extends Bindings {
  @override
  void dependencies() {
    Get.lazyPut(() => LoginController());
    Get.lazyPut(() => DashboardController());
    Get.lazyPut(() => DecisionsController());
    Get.lazyPut(() => DecisionsDetailsController());
    Get.lazyPut(() => HomeController());
    Get.lazyPut(() => MailController());
    Get.lazyPut(() => CreateMailController());
    Get.lazyPut(() => MailDetailsController());
    Get.lazyPut(() => MeetingsController());
    Get.lazyPut(() => MeetingsDetailsController());
    Get.lazyPut(() => VacationsController());
    Get.lazyPut(() => VacationsFormController());
    Get.lazyPut(() => VacationsStepsController());
    Get.lazyPut(() => SuccessVacationController());
    Get.lazyPut(() => NotificationsController());
    Get.lazyPut(() => EvaluationsController());
    Get.lazyPut(() => EvaluationsStepsController());
    Get.lazyPut(() => LoanController());
    Get.lazyPut(() => LoanDetailsController());
    Get.lazyPut(() => BonusController());
    Get.lazyPut(() => BonusDetailsController());
    Get.lazyPut(() => PunishmentsController());
    Get.lazyPut(() => PunishmentsDetailsController());
    Get.lazyPut(() => ComplaintController());
    Get.lazyPut(() => ComplaintDetailsController());
    Get.lazyPut(() => AlertController());
    Get.lazyPut(() => AlertDetailsController());
    Get.lazyPut(() => TicketController());
    Get.lazyPut(() => TicketDetailsController());
    Get.lazyPut(() => PurchaseController());
    Get.lazyPut(() => PunishmentsDetailsController());
    Get.lazyPut(() => CustodyController());
    Get.lazyPut(() => CustodyDetailsController());
    Get.lazyPut(() => SignInOutController());
    Get.lazyPut(() => SignInOutDetailsController());
    Get.lazyPut(() => SettingsController());
    Get.lazyPut(() => DeleteController());
  }
}
